### ISSUE TITLE
BOM for your multiboard

### ISSUE THREAD

**Issue by grymoire** [DrB0rk/Flipper-Zero-Boards#3]
I'd like to make your board, and I'm not good with Surface mount devices. If you have a Bill of Materials it would be useful when I have it assembled - using a company like JLCPCB, who will build the board for me.

**Comment by DrB0rk** [comment]
Hi, JLC has its own library, but i hand-picked and ordered them from a local store, so i don't think the BOM list will be compatible. i will offer fully assembled board on my Tindie though :)

**Comment by grymoire** [comment]
Thank you. I do appreciate your contribution.

**Comment by Bertus-W** [comment]
@DrB0rk Is it possible for you to share your shopping list basically? To see what the exact models of the components are?

**Comment by DrB0rk** [comment]
I'll update the repo as soon as I can, they're pretty standard components, I designed it to be so almost every component is smd 1206 sized. And for the caps the voltage doesn't really matter, only the capacitance does. 

Make sure to keep an eye out, I'll do it as soon as I can :)

**Comment by osysltd** [comment]
Hi! Can someone share BOM and CPL files with matching ones from the fresh database https://jlcpcb.com/parts?
Multi board v2 is awesome!

**Comment by Bertus-W** [comment]
@DrB0rk Hope you can get the list to us sometime, Was trying to do it myself but I don't really know what specific specs each component needs, or what is compatible, hope you can help me and others with this :). Received pcb's today, they look awesome

**Comment by grymoire** [comment]
I've published an updated BOM with LPLC part numbers (for PCLPCB) in the discord chat. I will published my BOM order once the V3 board's design is approved by the good doctor.
