### ISSUE TITLE
Part for dipswitch

### ISSUE THREAD

**Issue by Bertus-W** [DrB0rk/Flipper-Zero-Boards#6]
Hi, I was wondering if you could get me the specs for the dipswitch? I suppose it requires pretty specific measurements since it's packed against the nrf24 board.

**Comment by DrB0rk** [comment]
Hi, the dip switch is a bit of a weird size, I'm gonna change it to another one in the re-design. there are some problems with the current version. once i finished the design ill update the page with everything you need to know :)
