### ISSUE TITLE
Board Idea: Flipper CC1101

### ISSUE THREAD

**Issue by Phreak87** [DrB0rk/Flipper-Zero-Boards#7]
Hey, 

maybe it would be a great idea to add a secondary CC1101 to flipper.
this would make the flipper to a realy bad system because of the possibility
to bypass access systems with rolling code systems by sending out a blocking
signal while receiving the original signal - by pressing the key the second time send out
the first signal (then flipper has the next valid code to open)

**Comment by DrB0rk** [comment]
I'll see what I can do! I don't exactly know how the flipper handles reading and sending subghz signals. But this would be a great idea.
